---
title: "Dynamics and outliers"
author: "Javier Porras"
date: "`r Sys.Date()`"
output: 
  html_document: default
bibliography: references.bib
csl: citation_style/ecology.csl
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

```{r libraries}
library(tidyverse)
library(ggpubr)
library(lubridate)
library(stringr)
library(ggplot2)
library(dplyr)
library(reshape2)
library(readr)
library(ggpubr)
library(tidyverse)
library(gridExtra)
```

### Context

We have found that there is a number of **outliers** that prevent us from extracting a clear interpretation of the distribution of the morphological data. 


```{r}
library(dplyr)
flora_raw <- read.csv("data/flora_db.csv")
flora_raw <- flora_raw %>%
  mutate(across(where(is.character), as.factor))
desired_order <- c("s0_may", "s1_may", "s2_jun", "s3_jun", "s4_jul", "s5_jul", "s6_aug", 
                   "s7_sep", "s8_sep", "s9_oct", "s10_oct", "s11_nov")
flora_raw$sampling <- factor(flora_raw$sampling, levels = desired_order)

#Sumar 0.01 cm a los diámetros por el error del calibre con el que medimos
flora_raw$Dm <- flora_raw$Dm + 0.01
flora_raw$Db <- flora_raw$Db + 0.01

sampling_dates <- read.csv("data/sampling_dates.csv")
sampling_dates$datenew <-  ymd(sampling_dates$date)
sampling_dates$month <- month(sampling_dates$datenew)
sampling_dates$date <- NULL
sampling_dates$micro.sampling <- NULL
sampling_dates$N.micro <- NULL

sampling_dates <- sampling_dates %>%
  mutate(across(where(is.character), as.factor))
  
flora_raw <- right_join(flora_raw, sampling_dates, by = join_by(sampling))

flora <- flora_raw %>% select(sampling, plot, treatment, species, abundance, height, Cb, Db, Cm, Dm, datenew, month)

flora$cm <- round(ifelse(!is.na(flora$Dm), flora$Dm * pi, flora$Cm), 2)
flora$cb <- round(ifelse(!is.na(flora$Db), flora$Db * pi, flora$Cb), 2)
flora$Ah <- ((flora$cm)^2)/4*pi
flora$Ab <- ((flora$cb)^2)/4*pi

#Application of equation proposed by paper Perrone R. et al. 2020

d_perrone <- 1.96
z_perrone <- 2/3
flora$x <- (flora$height/2)*(flora$Ab + flora$Ah)
flora$biomass <- d_perrone*(flora$x^z_perrone)



par(mfrow = c(1,2))
hist(flora$x)
boxplot(flora$x)



```
*Histogram and boxplot of raw data*

If we remove outliers, we can easily see that our data follow an **asymmetrical** distribution: 

```{r Removing outliers}

flora1 <- flora[which(flora$x < (as.numeric(quantile(flora$x, na.rm = TRUE)[4] + (1.5 * IQR(flora$x, na.rm = TRUE))))),] 
flora3 <- flora[which(flora$x < (as.numeric(quantile(flora$x, na.rm = TRUE)[4] + (3 * IQR(flora$x, na.rm = TRUE))))),] 

#List of outliers: 
flora1_outl <- flora[which(flora$x > (as.numeric(quantile(flora$x, na.rm = TRUE)[4] + (1.5 * IQR(flora$x, na.rm = TRUE))))),] 
flora3_outl <- flora[which(flora$x > (as.numeric(quantile(flora$x, na.rm = TRUE)[4] + (3 * IQR(flora$x, na.rm = TRUE))))),] 

print(ggarrange(
ggplot(flora1, aes(y = x)) +
  geom_boxplot(),
ggplot(flora3, aes(y = x)) +
  geom_boxplot(),
labels = c("-outl", "-ext.outl"),
ncol = 2, nrow = 1))

par(mfrow = c(1, 2))
hist(flora1$x)
hist(flora3$x)
par(mfrow = c(1, 1))



```


### Dynamics 

How does the removing of outliers influence the biomass dynamics?

```{r}
#Data with outliers
flora <- flora %>%
  group_by(sampling, datenew, month, treatment, plot, abundance, species) %>%
  reframe(biomass = mean(biomass, na.rm = TRUE) * abundance) %>%
  distinct(sampling, datenew, month, plot, treatment, abundance, species, biomass)

flora <- flora %>%
  group_by(plot, sampling) %>%
  mutate(n_species = n()) %>%
  ungroup()

flora_samplings <-  flora %>%
  group_by(sampling, datenew, month, treatment, plot) %>%
  reframe(biomass = sum(biomass, na.rm = T), 
          n_species = n_species, 
          abundance = sum(abundance, na.rm = T)) %>%
  distinct(sampling, datenew, month, plot, treatment, biomass, n_species, abundance)

# without outliers
flora1 <- flora1 %>%
  group_by(sampling, datenew, month, treatment, plot, abundance, species) %>%
  reframe(biomass = mean(biomass, na.rm = TRUE) * abundance) %>%
  distinct(sampling, datenew, month, plot, treatment, abundance, species, biomass)
#! Esdte paso no es necesario ahora con flora1, ya que al generar la df hicimos un na.rm = T
#flora1$biomass <- ifelse(flora1$biomass == 0, NA, flora1$biomass)

flora1 <- flora1 %>%
  group_by(plot, sampling) %>%
  mutate(n_species = n()) %>%
  ungroup()

flora1_samplings <-  flora1 %>%
  group_by(sampling, datenew, month, treatment, plot) %>%
  reframe(biomass = sum(biomass, na.rm = T), 
          n_species = n_species, 
          abundance = sum(abundance, na.rm = T)) %>%
  distinct(sampling, datenew, month, plot, treatment, biomass, n_species, abundance)


# without extreme outliers
flora3 <- flora3 %>%
  group_by(sampling, datenew, month, treatment, plot, abundance, species) %>%
  reframe(biomass = mean(biomass, na.rm = TRUE) * abundance) %>%
  distinct(sampling, datenew, month, plot, treatment, abundance, species, biomass)

flora3 <- flora3 %>%
  group_by(plot, sampling) %>%
  mutate(n_species = n()) %>%
  ungroup()

flora3_samplings <-  flora3 %>%
  group_by(sampling, datenew, month, treatment, plot) %>%
  reframe(biomass = sum(biomass, na.rm = T), 
          n_species = n_species, 
          abundance = sum(abundance, na.rm = T)) %>%
  distinct(sampling, datenew, month, plot, treatment, biomass, n_species, abundance)


#Graphs: 


ggplot(flora_samplings, aes(x = sampling, y = biomass, color = treatment)) +
  geom_boxplot() +
  labs(x = " ", y = "Biomass") +
  scale_color_manual(values = c("c" = "green", "p" = "blue", "w" = "red", "wp" = "purple")) +
  theme_minimal() +
  geom_vline(xintercept = 1.5, linetype = "dotted", color = "maroon", size = 0.8) +
  theme(legend.position = "none", 
        axis.text = element_text(size = 12))

ggplot(flora1_samplings, aes(x = sampling, y = biomass, color = treatment)) +
  geom_boxplot() +
  labs(x = " ", y = "Biomass") +
  scale_color_manual(values = c("c" = "green", "p" = "blue", "w" = "red", "wp" = "purple")) +
  theme_minimal() +
  theme(legend.position = "none", 
        axis.text = element_text(size = 12))

ggplot(flora3_samplings, aes(x = sampling, y = biomass, color = treatment)) +
  geom_boxplot() +
  labs(x = " ", y = "Biomass") +
  scale_color_manual(values = c("c" = "green", "p" = "blue", "w" = "red", "wp" = "purple")) +
  theme_minimal() +
  theme(legend.position = "bottom", 
        axis.text = element_text(size = 12))



```




