---
title: "Species composition"
author: "Javier Porras"
date: "`r Sys.Date()`"
bibliography: references.bib
csl: citation_style/ecology.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)
```

```{r libraries}
library(tidyverse)
library(ggpubr)
library(lubridate)
library(stringr)
library(ggplot2)
library(dplyr)
library(reshape2)
library(readr)
library(ggpubr)
library(tidyverse)
library(gridExtra)
```

### Context


```{r Opening data}
library(dplyr)
flora_raw <- read.csv("data/flora_db.csv")
flora_raw <- flora_raw %>%
  mutate(across(where(is.character), as.factor))
desired_order <- c("s0_may", "s1_may", "s2_jun", "s3_jun", "s4_jul", "s5_jul", "s6_aug", 
                   "s7_sep", "s8_sep", "s9_oct", "s10_oct", "s11_nov")
flora_raw$sampling <- factor(flora_raw$sampling, levels = desired_order)

sampling_dates <- read.csv("data/sampling_dates.csv")
summary(sampling_dates)
str(sampling_dates)
sampling_dates$datenew <-  ymd(sampling_dates$date)
sampling_dates$month <- month(sampling_dates$datenew)
sampling_dates$date <- NULL
sampling_dates$micro.sampling <- NULL
sampling_dates$N.micro <- NULL

sampling_dates <- sampling_dates %>%
  mutate(across(where(is.character), as.factor))
  
flora_raw <- right_join(flora_raw, sampling_dates, by = join_by(sampling))

flora <- flora_raw %>% select(sampling, plot, treatment, species, abundance, height, Cb, Db, Cm, Dm, datenew, month)

```

